{
            "config": {
                "memory_slots": 2,
                "n_qubits": 14
            },
            "header": {
                "clbit_labels": [
                    [
                        "c0",
                        0
                    ],
                    [
                        "c0",
                        1
                    ]
                ],
                "compiled_circuit_qasm": "OPENQASM 2.0;\ninclude \"qelib1.inc\";\nqreg q[14];\ncreg c0[2];\nu2(0,pi) q[1];\ncx q[1],q[0];\nu2(0,pi) q[1];\nu2(0,pi) q[0];\nbarrier q[0],q[1];\nmeasure q[1] -> c0[1];\nmeasure q[0] -> c0[0];\n",
                "creg_sizes": [
                    [
                        "c0",
                        2
                    ]
                ],
                "memory_slots": 2,
                "n_qubits": 14,
                "name": "circuit0",
                "qreg_sizes": [
                    [
                        "q",
                        14
                    ]
                ],
                "qubit_labels": [
                    [
                        "q",
                        0
                    ],
                    [
                        "q",
                        1
                    ],
                    [
                        "q",
                        2
                    ],
                    [
                        "q",
                        3
                    ],
                    [
                        "q",
                        4
                    ],
                    [
                        "q",
                        5
                    ],
                    [
                        "q",
                        6
                    ],
                    [
                        "q",
                        7
                    ],
                    [
                        "q",
                        8
                    ],
                    [
                        "q",
                        9
                    ],
                    [
                        "q",
                        10
                    ],
                    [
                        "q",
                        11
                    ],
                    [
                        "q",
                        12
                    ],
                    [
                        "q",
                        13
                    ]
                ]
            },
            "instructions": [
                {
                    "memory": [],
                    "name": "u2",
                    "params": [
                        0.0,
                        3.141592653589793
                    ],
                    "qubits": [
                        1
                    ],
                    "texparams": [
                        "0",
                        "\\pi"
                    ]
                },
                {
                    "memory": [],
                    "name": "cx",
                    "params": [],
                    "qubits": [
                        1,
                        0
                    ],
                    "texparams": []
                },
                {
                    "memory": [],
                    "name": "u2",
                    "params": [
                        0.0,
                        3.141592653589793
                    ],
                    "qubits": [
                        0
                    ],
                    "texparams": [
                        "0",
                        "\\pi"
                    ]
                },
                {
                    "memory": [],
                    "name": "u2",
                    "params": [
                        0.0,
                        3.141592653589793
                    ],
                    "qubits": [
                        1
                    ],
                    "texparams": [
                        "0",
                        "\\pi"
                    ]
                },
                {
                    "memory": [],
                    "name": "barrier",
                    "params": [],
                    "qubits": [
                        0,
                        1
                    ],
                    "texparams": []
                },
                {
                    "memory": [
                        0
                    ],
                    "name": "measure",
                    "params": [],
                    "qubits": [
                        0
                    ],
                    "texparams": []
                },
                {
                    "memory": [
                        1
                    ],
                    "name": "measure",
                    "params": [],
                    "qubits": [
                        1
                    ],
                    "texparams": []
                }
            ]
}
